name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure secret.py file
      run: |
        python -c "import os; file = open('secret.py', 'w'); file.write(f'OPEN_WEATHER_API = \'{os.environ['OPEN_WEATHER_API']}\'; WEATHER_API = \'{os.environ['WEATHER_API']}\''); file.close()"
      shell: bash
      env:
        OPEN_WEATHER_API : ${{secrets.OPEN_WEATHER_API}}
        WEATHER_API : ${{secrets.WEATHER_API}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Wait for deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        command="gh api -H 'X-GitHub-Api-Version: 2022-11-28' /repos/${{ github.repository }}/deployments?ref=${{ github.sha }}
        | jq -r '.[0].payload.web_url | select ( . != null)'"
        while [ true ]; do
        url="$(eval $command)";
        if [ -z "$url" ]; then
            echo "Deployment not ready yet, waiting..."
            sleep 5
        else
            echo "Deployment ready at $url"
            echo "BASE_URL=$url" >> $GITHUB_ENV
            break
        fi
        done
